# Generated by Django 5.2.13 on 2026-05-18 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='ключ сессии')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='просмотрено')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='ads.advertisement', verbose_name='объявление')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_views', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'просмотр объявления',
                'verbose_name_plural': 'история просмотров',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='ads_adview_user_id_df77bc_idx'), models.Index(fields=['session_key', '-viewed_at'], name='ads_adview_session_cfe34c_idx')],
            },
        ),
    ]
